name: React CI/CD

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build
    - run: mv /actions-runner/dash-admin/dashboard-admin/dashboard-admin/dist /actions-runner/dash-admin/dashboard-admin/dashboard-admin/dashadmin
